apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations:
        version: "DEV"
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ccsadmindocker/geekbackend:DEV
        imagePullPolicy: Always
        env:
        - name: DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DATASOURCE_URL
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASS

        ports:
        - containerPort: 8080

---

# Temp Service to check backend
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

